# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
board.c
heap.c
drv_uart.c
drv_sd.c
drv_net.c
vm.c
''')
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')


#emacps/xemacps.c
#emacps/xemacps_bdring.c
#emacps/xemacps_control.c
#emacps/xemacps_example_util.c
#emacps/xemacps_g.c
#emacps/xemacps_hw.c
#emacps/xemacps_intr.c
#emacps/xemacps_main.c
#