Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')

include_path = Split("""
libmetal/lib/include
libmetal/test
libmetal/lib/include/metal/processor
open-amp/lib/include
""")

# For open-amp platform_info.h
include_path += ['open-amp/apps/system/rtthread/machine/generic']

src = Split("""
libmetal/lib/device.c
libmetal/lib/log.c
libmetal/lib/init.c
libmetal/lib/system/rtthread/io.c
libmetal/lib/system/rtthread/device.c
libmetal/lib/system/rtthread/init.c
libmetal/lib/system/rtthread/riscv/sys.c
""")

src += ['libmetal/test/system/rtthread/atomic.c']
src += ['libmetal/test/system/rtthread/mutex.c']

src += Split("""
libmetal/test/metal-test.c
libmetal/test/system/rtthread/main.c
libmetal/test/system/rtthread/threads.c
""")

# src += ['open-amp/apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = include_path, CPPDEFINES = ['DEFAULT_LOGGER_ON'])

Return('group')
