Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')

include_path = Split("""
libmetal/lib/include
libmetal/test
libmetal/lib/include/metal/processor
open-amp/lib/include
""")

src = Split("""
libmetal/lib/device.c
libmetal/lib/log.c
libmetal/lib/init.c
libmetal/lib/system/rtthread/io.c
libmetal/lib/system/rtthread/device.c
libmetal/lib/system/rtthread/init.c
libmetal/lib/system/rtthread/riscv/sys.c
""")

src += ['libmetal/test/system/rtthread/atomic.c']
src += ['libmetal/test/system/rtthread/mutex.c']
src += ['libmetal/examples/system/rtthread/shmem_demod.c']

src += Split("""
libmetal/test/metal-test.c
libmetal/test/system/rtthread/main.c
libmetal/test/system/rtthread/threads.c
""")

src += ['libmetal/lib/io.c']
src += ['libmetal/lib/shmem.c']
include_path += ['open-amp/apps/system/generic/machine/rv64_virt']
include_path += ['open-amp/lib/rpmsg']
include_path += ['open-amp/lib/include/openamp']

src += ['open-amp/apps/examples/rpmsg_sample_echo/rpmsg-sample-echo.c']
src += ['open-amp/apps/tests/msg/rpmsg-update.c']
src += ['open-amp/apps/examples/matrix_multiply/matrix_multiplyd.c']
src += ['open-amp/apps/system/generic/machine/rv64_virt/virt_rv64_rproc.c']
src += ['open-amp/apps/system/generic/machine/rv64_virt/helper.c']
src += ['open-amp/apps/system/generic/machine/rv64_virt/platform_info.c']
src += ['open-amp/apps/system/generic/machine/rv64_virt/rsc_table.c']
src += ['open-amp/lib/rpmsg/rpmsg.c']
src += ['open-amp/lib/rpmsg/rpmsg_virtio.c']
src += ['open-amp/lib/proxy/rpmsg_retarget.c']
src += ['open-amp/lib/remoteproc/rsc_table_parser.c']
src += ['open-amp/lib/remoteproc/remoteproc_virtio.c']
src += ['open-amp/lib/remoteproc/elf_loader.c']
src += ['open-amp/lib/remoteproc/remoteproc.c']
src += ['open-amp/lib/virtio/virtqueue.c']
src += ['open-amp/lib/virtio/virtio.c']

CPPDEFINES = []
CPPDEFINES += ['DEFAULT_LOGGER_ON']
CPPDEFINES += ['RPMSG_NO_IPI']
group = DefineGroup('Applications', src, depend = [''], CPPPATH = include_path, CPPDEFINES = CPPDEFINES)

Return('group')
